# menu
menu:
  home:
    href: /
    title: 首 页
  archives:
    href: /archives
    title: 归 档
  tags:
    href: /tags
    title: 标 签
  links:
    href: /about
    title: 关 于
  
# rss
rss: /atom.xml

# avatar
avatar: /assets/images/logo.jpg

# Content
tags:
  title: 标签

# mathjax
mathjax: false

# archive
archive_yearly: true

# share
share: true

# search
search: true

# 
hideMenu: true

# toc
toc:
  list_number: false  # 是否显示数字排序

# favicon
favicon: /favicon.ico

# less
less:
  paths:
    - source/css/style.less

# comment
duoshuo: qinyuanpei

# award
award:
  license: by-nc-nd
  copyright: 本文采用国际知识共享“<b>署名</b>-<b>非商业使用</b>-<b>禁止演绎</b>”协议4.0进行授权许可。未经本人同意禁止转载本文内容，转载请注明作者姓名和文章出处。

# reard
reward:
  weixin: /assets/images/weixin.png 
  alipay: /assets/images/alipay.png
  
